### ISSUE TITLE
Using unseen classes GT labels make no sense for zero-shot setting

### ISSUE THREAD

**Issue by zbf1991** [valeoai/zero_shot_semantic_segmentation#10] opened 2020-12-01 05:55 UTC
As discussed in other issues, some unseen classes GT labels are used in this code. However, in the zero-shot setting, it is unsuitable since we do not know anything about the unseen classes except its name. Using some unseen classes GT labels is more like to process a semi-supervised task rather than a zero-shot task.

**Comment by tuanhungvu** [comment] 2020-12-02 09:21
Duplicate of #4

**Closed as completed by tuanhungvu** 2020-12-02 09:21 UTC

**Comment by zbf1991** [comment] 2020-12-04 09:01
You mentioned you will update a new version in #4 ,  does the new version still use unseen GT labels? and When will you update?

**Comment by tuanhungvu** [comment] 2020-12-08 18:38
Hello @zbf1991,  I want to explain a bit more to clear up your concerns.

We here address the task of semantic segmentation: in one scene there are pixels coming from many classes, possibly from both seen and unseen classes. However, a clean zero-shot set-up should be that training images only contain seen classes. The act of using unseen GT in our code is just to select the training subset (subset-1) containing no unseen objects while training the feature generator.

The training subset having both seen and unseen objects (subset-2) is not used to train the generator. Only when training the conv 1x1 classifier, we do know the amount of pixels of unseen objects coming from subset-2. However, we don't think that is a serious issue which violates the zero-shot principles.
To have a cleaner set-up, when training the classifier, one can simply select random amounts of unseen pixels. Or to be more "real world compatible", in #4 we suggest another way to infer such unseen statistics. Either way, one could only use subset-1 as the training set, or use both subsets with ignore flags on unseen pixels. At the moment, we don't have the bandwidth for such implementations. Any help is welcome.

Best,
T-H
